#!/usr/bin/env ruby

require 'erb'

load "/etc/freewvs/freewvs_check.conf"

DIR = File.dirname(__FILE__)

result = `#{DIR}/freewvs/freewvs -x /var/www/`
entries = {}

MAILMAPPING ||= {}

begin
  result =~ /<app state="vulnerable">(.+?)<\/app>(.*)/m
  entry  = $1
  result = $2
  entry  =~ /<directory>(.+)<\/directory>/
  dir    = $1
  host   = dir.split("/")[4]
  dir   = dir.split("/")[5..-1].join("/")
  entries[host]    ||= {}
  entries[host][dir] = {}
  entry  =~ /<appname>(.+)<\/appname>/
  entries[host][dir][:app] = $1
  entry  =~ /<version>(.+)<\/version>/
  entries[host][dir][:version] = $1
  entry  =~ /<safeversion>(.+)<\/safeversion>/
  entries[host][dir][:safe_version] = $1
  entry  =~ /<vulninfo>(.+)<\/vulninfo>/
  entries[host][dir][:cve] = $1
end while result =~ /<app/

template = File.read('/etc/freewvs/freewvs_check.erb')

entries.each do |host,folders|
  renderer = ERB.new(template)
  @host    = host
  @folders = folders

  domain   = MAILMAPPING[host]
  if hostpart.size > 1
    domain ||= hostpart[-2..-1].join(".")
  else
    domain ||= host
  end
  mail     = "security@#{domain}"
  text     = renderer.result()

  `sendmail -f #{SENDER} #{mail} <<EOF
#{text}
EOF`
end
