#!/usr/bin/env ruby

DIR = File.dirname(__FILE__)

load "#{DIR}/freewvs_check.conf"

result = `#{DIR}/freewvs/freewvs -x /var/www/`
entries = {}

MAILMAPPING ||= {}

begin
  result =~ /<app state="vulnerable">(.+?)<\/app>(.*)/m
  entry  = $1
  result = $2
  entry  =~ /<directory>(.+)<\/directory>/
  dir    = $1
  host   = dir.split("/")[4]
  dir   = dir.split("/")[5..-1].join("/")
  entries[host]    ||= {}
  entries[host][dir] = {}
  entry  =~ /<appname>(.+)<\/appname>/
  entries[host][dir][:app] = $1
  entry  =~ /<version>(.+)<\/version>/
  entries[host][dir][:version] = $1
  entry  =~ /<safeversion>(.+)<\/safeversion>/
  entries[host][dir][:safe_version] = $1
  entry  =~ /<vulninfo>(.+)<\/vulninfo>/
  entries[host][dir][:cve] = $1
end while result =~ /<app/


entries.each do |host,folders|
  text    = HOST_TEMPLATE.gsub('$host',host)
  text_en = HOST_EN_TEMPLATE.gsub('$host',host)
  folders.each do |folder,info|
    text    += FOLDER_TEMPLATE.gsub('$folder',folder)
    text_en += FOLDER_EN_TEMPLATE.gsub('$folder',folder)
    text.gsub!('$version',info[:version])
    text.gsub!('$appname',info[:app])
    text.gsub!('$cve',info[:cve])
    text_en.gsub!('$version',info[:version])
    text_en.gsub!('$appname',info[:app])
    text_en.gsub!('$cve',info[:cve])
  end
  text    += FOOTER_TEMPLATE
  text_en += FOOTER_EN_TEMPLATE

  domain = host.split(".")[-2..-1].join(".")
  mail   = MAILMAPPING[host]
  mail ||= MAILMAPPING[domain]
  mail ||= "security@#{domain}"
  text   = "#{text}\n-------------------\n#{text_en}"

  `sendmail -f #{SENDER} #{mail} <<EOF
Subject: #{SUBJECT}
Content-Type: text/plain; charset=UTF-8

#{text}
EOF`
end
